export const data = [
  {
    title: "First Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "99",
    currency: "TL",
    quantity: 23,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/1.jpg",
  },
  {
    title: "Second Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/2.jpg",
  },
  {
    title: "Third Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/3.jpg",
  },
  {
    title: "Fourth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/4.jpg",
  },
  {
    title: "Fifth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/5.jpg",
  },
  {
    title: "Sixth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/6.jpg",
  },
  {
    title: "Seventh Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/7.jpg",
  },
  {
    title: "Eighth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/8.jpg",
  },
  {
    title: "Ninth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/9.jpg",
  },
  {
    title: "Tenth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/10.jpg",
  },
  {
    title: "Elenth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/11.jpg",
  },
  {
    title: "Twelvth Product",
    description:
      "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
    link: "https://www.google.com",
    price: "105",
    currency: "TL",
    quantity: 78,
    brand: "DAMAT",
    color: "Blue",
    gender: "Male",
    gtin: "ABC123",
    mpn: "123XYZ",
    condition: "New",
    picture: "/pictures/12.jpg",
  },
];
